name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**

env:
  IMAGE_NAME: nodejs-app
  CONTAINER_NAME: nodejs-app
  APP_PORT: 80

jobs:
  setup-docker:
    runs-on: self-hosted
    steps:
      - name: Check and install Docker
        run: |
          chmod +x ./scripts/check_docker.sh
          ./scripts/check_docker.sh

  build-and-deploy:
    runs-on: self-hosted
    needs: setup-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh ${{ env.IMAGE_NAME }} ${{ env.CONTAINER_NAME }} ${{ env.APP_PORT }}

      - name: Health check
        run: |
          echo "Checking application health..."
          for i in {1..10}; do
            if curl -s http://localhost:${{ env.APP_PORT }} > /dev/null; then
              echo "Application is healthy!"
              exit 0
            else
              echo "Waiting for application to become healthy..."
              sleep 2
            fi
          done
          echo "Application did not start in time."
          exit 1
